name: bokers
favicon: null
layout_spectrum: 0.23437281954102218
typography_spectrum: 0.771463805809617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.37752443132922053
  lightness: 0.8563775878865272
  saturation: 0.43725630664266646
  rhythmicContrast: 0.9587548382114619
purpose: []
